// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  '/': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : '/'}`;
  },
  '/confirmation': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/confirmation`;
  },
  '/forgot-password': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/forgot-password`;
  },
  '/invitation': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/invitation`;
  },
  '/login': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/login`;
  },
  '/privacy-policy': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/privacy-policy`;
  },
  '/reset-password': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/reset-password`;
  },
  '/sign-up': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/sign-up`;
  },
  '/souhlas-se-zpracovanim-osobnich-udaju': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/souhlas-se-zpracovanim-osobnich-udaju`;
  },
  '/anamnestic': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/anamnestic`;
  },
  '/dashboard': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/dashboard`;
  },
  '/doctors': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/doctors`;
  },
  '/doctors/[doctorId]': (params: { doctorId: string | number; locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/doctors/${params.doctorId}`;
  },
  '/doctors/[doctorId]/contact': (params: {
    doctorId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/doctors/${params.doctorId}/contact`;
  },
  '/doctors/new': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/doctors/new`;
  },
  '/entries': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/entries`;
  },
  '/export': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/export`;
  },
  '/patients/approved': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved`;
  },
  '/patients/approved/[patientId]': (params: {
    patientId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}`;
  },
  '/patients/approved/[patientId]/anamnestic/[anamnesticFormId]': (params: {
    patientId: string | number;
    anamnesticFormId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/anamnestic/${params.anamnesticFormId}`;
  },
  '/patients/approved/[patientId]/first-appointment/[firstAppointmentId]': (params: {
    patientId: string | number;
    firstAppointmentId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/first-appointment/${params.firstAppointmentId}`;
  },
  '/patients/approved/[patientId]/first-appointment/new': (params: {
    patientId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/first-appointment/new`;
  },
  '/patients/approved/[patientId]/iciq/[iciqFormId]': (params: {
    patientId: string | number;
    iciqFormId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/iciq/${params.iciqFormId}`;
  },
  '/patients/approved/[patientId]/initial-appointment/[initialAppointmentId]': (params: {
    patientId: string | number;
    initialAppointmentId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/initial-appointment/${params.initialAppointmentId}`;
  },
  '/patients/approved/[patientId]/initial-appointment/new': (params: {
    patientId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/initial-appointment/new`;
  },
  '/patients/approved/[patientId]/ipss/[ipssFormId]': (params: {
    patientId: string | number;
    ipssFormId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/ipss/${params.ipssFormId}`;
  },
  '/patients/approved/[patientId]/oab/[oabFormId]': (params: {
    patientId: string | number;
    oabFormId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/oab/${params.oabFormId}`;
  },
  '/patients/approved/[patientId]/second-appointment/[secondAppointmentId]': (params: {
    patientId: string | number;
    secondAppointmentId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/second-appointment/${params.secondAppointmentId}`;
  },
  '/patients/approved/[patientId]/second-appointment/new': (params: {
    patientId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/second-appointment/new`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]': (params: {
    patientId: string | number;
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/edit': (params: {
    patientId: string | number;
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/edit`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records': (params: {
    patientId: string | number;
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/input/[recordId]': (params: {
    patientId: string | number;
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records/input/${params.recordId}`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/input/[recordId]/edit': (params: {
    patientId: string | number;
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records/input/${params.recordId}/edit`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/input/new': (params: {
    patientId: string | number;
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records/input/new`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/output/[recordId]': (params: {
    patientId: string | number;
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records/output/${params.recordId}`;
  },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/output/[recordId]/edit':
    (params: {
      patientId: string | number;
      diaryId: string | number;
      recordId: string | number;
      locale?: string | number;
    }) => {
      return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records/output/${params.recordId}/edit`;
    },
  '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/output/new': (params: {
    patientId: string | number;
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/${params.diaryId}/records/output/new`;
  },
  '/patients/approved/[patientId]/voiding-diary/new': (params: {
    patientId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/approved/${params.patientId}/voiding-diary/new`;
  },
  '/patients/to-be-approved': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/patients/to-be-approved`;
  },
  '/questionnaires': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/questionnaires`;
  },
  '/questionnaires/iciq': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/questionnaires/iciq`;
  },
  '/questionnaires/ipss': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/questionnaires/ipss`;
  },
  '/users/[userId]': (params: { userId: string | number; locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/users/${params.userId}`;
  },
  '/voiding-diary': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary`;
  },
  '/voiding-diary/list': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list`;
  },
  '/voiding-diary/list/[diaryId]': (params: {
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}`;
  },
  '/voiding-diary/list/[diaryId]/edit': (params: {
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/edit`;
  },
  '/voiding-diary/list/[diaryId]/records': (params: {
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records`;
  },
  '/voiding-diary/list/[diaryId]/records/input/[recordId]': (params: {
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records/input/${params.recordId}`;
  },
  '/voiding-diary/list/[diaryId]/records/input/[recordId]/edit': (params: {
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records/input/${params.recordId}/edit`;
  },
  '/voiding-diary/list/[diaryId]/records/input/new': (params: {
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records/input/new`;
  },
  '/voiding-diary/list/[diaryId]/records/output/[recordId]': (params: {
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records/output/${params.recordId}`;
  },
  '/voiding-diary/list/[diaryId]/records/output/[recordId]/edit': (params: {
    diaryId: string | number;
    recordId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records/output/${params.recordId}/edit`;
  },
  '/voiding-diary/list/[diaryId]/records/output/new': (params: {
    diaryId: string | number;
    locale?: string | number;
  }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/${params.diaryId}/records/output/new`;
  },
  '/voiding-diary/list/new': (params?: { locale?: string | number }) => {
    return `${params?.locale ? `/${params?.locale}` : ''}/voiding-diary/list/new`;
  },
};

/**
 * SERVERS
 */
const SERVERS = {};

/**
 * ACTIONS
 */
const ACTIONS = {};

/**
 * LINKS
 */
const LINKS = {};

type ParamValue = string | number | undefined;

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?'
) => {
  if (sp === undefined) return '';

  const params = new URLSearchParams();
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v));
    }
  };

  for (const [name, val] of Object.entries(sp)) {
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v);
      }
    } else {
      append(name, val);
    }
  }

  const formatted = params.toString();
  if (formatted) {
    return `${prefix}${formatted}`;
  }
  return '';
};

/**
 * get the current search params
 *
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search);
  const record: Record<string, string> = {};
  for (const [key, value] of params.entries()) {
    record[key] = value;
  }
  return record;
};

// route function helpers
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T];
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T];
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never;

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS };
type AllTypes = typeof AllObjs;

export type Routes = keyof AllTypes extends `${string}/${infer Route}`
  ? `/${Route}`
  : keyof AllTypes;
export const routes = [
  ...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[];

/**
 * To be used like this:
 * ```ts
 * import { route } from './ROUTES'
 *
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(
  key: T,
  ...params: FunctionParams<AllTypes[T]>
): string;
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string;
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if ((AllObjs[key] as any) instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string;
    return element(...params);
  } else {
    return AllObjs[key] as string;
  }
}

/**
 * Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
 *
 * Full example:
 * ```ts
 * import type { KIT_ROUTES } from './ROUTES'
 * import { kitRoutes } from 'vite-plugin-kit-routes'
 *
 * kitRoutes<KIT_ROUTES>({
 *  PAGES: {
 *    // here, key of object will be typed!
 *  }
 * })
 * ```
 */
export type KIT_ROUTES = {
  PAGES: {
    '/': 'locale';
    '/confirmation': 'locale';
    '/forgot-password': 'locale';
    '/invitation': 'locale';
    '/login': 'locale';
    '/privacy-policy': 'locale';
    '/reset-password': 'locale';
    '/sign-up': 'locale';
    '/souhlas-se-zpracovanim-osobnich-udaju': 'locale';
    '/anamnestic': 'locale';
    '/dashboard': 'locale';
    '/doctors': 'locale';
    '/doctors/[doctorId]': 'doctorId' | 'locale';
    '/doctors/[doctorId]/contact': 'doctorId' | 'locale';
    '/doctors/new': 'locale';
    '/entries': 'locale';
    '/export': 'locale';
    '/patients/approved': 'locale';
    '/patients/approved/[patientId]': 'patientId' | 'locale';
    '/patients/approved/[patientId]/anamnestic/[anamnesticFormId]':
      | 'patientId'
      | 'anamnesticFormId'
      | 'locale';
    '/patients/approved/[patientId]/first-appointment/[firstAppointmentId]':
      | 'patientId'
      | 'firstAppointmentId'
      | 'locale';
    '/patients/approved/[patientId]/first-appointment/new': 'patientId' | 'locale';
    '/patients/approved/[patientId]/iciq/[iciqFormId]': 'patientId' | 'iciqFormId' | 'locale';
    '/patients/approved/[patientId]/initial-appointment/[initialAppointmentId]':
      | 'patientId'
      | 'initialAppointmentId'
      | 'locale';
    '/patients/approved/[patientId]/initial-appointment/new': 'patientId' | 'locale';
    '/patients/approved/[patientId]/ipss/[ipssFormId]': 'patientId' | 'ipssFormId' | 'locale';
    '/patients/approved/[patientId]/oab/[oabFormId]': 'patientId' | 'oabFormId' | 'locale';
    '/patients/approved/[patientId]/second-appointment/[secondAppointmentId]':
      | 'patientId'
      | 'secondAppointmentId'
      | 'locale';
    '/patients/approved/[patientId]/second-appointment/new': 'patientId' | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]': 'patientId' | 'diaryId' | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/edit':
      | 'patientId'
      | 'diaryId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records':
      | 'patientId'
      | 'diaryId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/input/[recordId]':
      | 'patientId'
      | 'diaryId'
      | 'recordId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/input/[recordId]/edit':
      | 'patientId'
      | 'diaryId'
      | 'recordId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/input/new':
      | 'patientId'
      | 'diaryId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/output/[recordId]':
      | 'patientId'
      | 'diaryId'
      | 'recordId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/output/[recordId]/edit':
      | 'patientId'
      | 'diaryId'
      | 'recordId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/[diaryId]/records/output/new':
      | 'patientId'
      | 'diaryId'
      | 'locale';
    '/patients/approved/[patientId]/voiding-diary/new': 'patientId' | 'locale';
    '/patients/to-be-approved': 'locale';
    '/questionnaires': 'locale';
    '/questionnaires/iciq': 'locale';
    '/questionnaires/ipss': 'locale';
    '/users/[userId]': 'userId' | 'locale';
    '/voiding-diary': 'locale';
    '/voiding-diary/list': 'locale';
    '/voiding-diary/list/[diaryId]': 'diaryId' | 'locale';
    '/voiding-diary/list/[diaryId]/edit': 'diaryId' | 'locale';
    '/voiding-diary/list/[diaryId]/records': 'diaryId' | 'locale';
    '/voiding-diary/list/[diaryId]/records/input/[recordId]': 'diaryId' | 'recordId' | 'locale';
    '/voiding-diary/list/[diaryId]/records/input/[recordId]/edit':
      | 'diaryId'
      | 'recordId'
      | 'locale';
    '/voiding-diary/list/[diaryId]/records/input/new': 'diaryId' | 'locale';
    '/voiding-diary/list/[diaryId]/records/output/[recordId]': 'diaryId' | 'recordId' | 'locale';
    '/voiding-diary/list/[diaryId]/records/output/[recordId]/edit':
      | 'diaryId'
      | 'recordId'
      | 'locale';
    '/voiding-diary/list/[diaryId]/records/output/new': 'diaryId' | 'locale';
    '/voiding-diary/list/new': 'locale';
  };
  SERVERS: Record<string, never>;
  ACTIONS: Record<string, never>;
  LINKS: Record<string, never>;
  Params: {
    locale: never;
    doctorId: never;
    patientId: never;
    anamnesticFormId: never;
    firstAppointmentId: never;
    iciqFormId: never;
    initialAppointmentId: never;
    ipssFormId: never;
    oabFormId: never;
    secondAppointmentId: never;
    diaryId: never;
    recordId: never;
    userId: never;
  };
};
